"""Add student_id to booking

Revision ID: 09978a9f41c0
Revises: 199b593a679f
Create Date: 2024-09-29 22:06:56.798307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09978a9f41c0'
down_revision = '199b593a679f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        # Add student_id while keeping student_name
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_student_id', 'user', ['student_id'], ['id'])
        # Do not drop student_name; keep it in the table
        # batch_op.drop_column('student_name')  # Remove or comment this line to keep student_name

    with op.batch_alter_table('tutor', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=200), nullable=True))

    with op.batch_alter_table('booking', schema=None) as batch_op:
        # Add student_name back in case of downgrade
        batch_op.add_column(sa.Column('student_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint('fk_student_id', 'booking', type_='foreignkey')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
