"""Add student_name to Booking model

Revision ID: 830e9a9bd2a8
Revises: 09978a9f41c0
Create Date: 2024-09-30 00:08:29.985052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830e9a9bd2a8'
down_revision = '09978a9f41c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_name', sa.String(length=100), nullable=False))
        batch_op.drop_constraint('fk_student_id', type_='foreignkey')
        batch_op.drop_column('student_id')

    with op.batch_alter_table('tutor', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=200), nullable=True))

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_student_id', 'user', ['student_id'], ['id'])
        batch_op.drop_column('student_name')

    # ### end Alembic commands ###
